language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install setuptools==33.1.1
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - py.test